FROM golang:1.9-alpine as builder

ARG LDFLAGS
ENV PACKAGE code.linksmart.eu/sc/service-catalog

# copy code
COPY . /home/src/${PACKAGE}

# build
ENV GOPATH /home
RUN go install -ldflags "${LDFLAGS}" ${PACKAGE}

###########
FROM alpine
LABEL maintainer="dev@linksmart.eu"

RUN apk update && apk add ca-certificates

WORKDIR /home
COPY --from=builder /home/bin/* .
COPY sample_conf/* /conf/

ENV SC_DNSSDENABLED=false
ENV SC_STORAGE_TYPE=leveldb
ENV SC_STORAGE_DSN=/data

VOLUME /conf /data
EXPOSE 8082

ENTRYPOINT ["./service-catalog"]
CMD ["-conf", "/conf/service-catalog.json"]